version: '3.8'
services:
  colloq-db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  colloq-api:
    build:
      context: ./colloquium/
      target: development
      dockerfile: ./dockerfile
    volumes:
      - ./colloquium:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn dev
    depends_on:
      - colloq-db
